name: sonar

on:
  workflow_call:
    inputs:
      node:
        description: 'Node version'
        default: '16'
        required: false
        type: string  
      artifact:
        description: 'Name of the artifact for the build'
        default: 'package'
        required: false
        type: string   
      artifactPath:
        description: 'Artifact path'
        default: '.'
        required: false
        type: string

jobs:
  sonar:
    name: sonar qa
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # setup node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node }}
          cache: 'npm'        
      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact }}
          path: ${{ inputs.artifactPath }}
      - name: Sonar publish analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
          SONAR_URL: 'https://sonarcloud.io'
        run: |
          SONAR_KEY="${GITHUB_REPOSITORY//\//_}"   
          OPS="-Dsonar.projectKey=$SONAR_KEY"
          OPS="$OPS -Dsonar.host.url=$SONAR_URL"
          OPS="$OPS -Dsonar.organization=${{ github.repository_owner }}"
          OPS="$OPS -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info"
          OPS="$OPS -Dsonar.testExecutionReportPaths=./coverage/sonarqube_report.xml"
          npx sonarqube-scanner $OPS -Dsonar.token=${{ secrets.SONAR_TOKEN }}

