name: sonar

on:
  workflow_call:
    inputs:
      python:
        description: 'Python version'
        default: '3.10'
        required: false
        type: string  
      artifact:
        description: 'Name of the artifact for the build'
        default: 'package'
        required: false
        type: string   
      artifactPath:
        description: 'Artifact path'
        default: '.'
        required: false
        type: string

jobs:
  sonar:
    name: sonar qa
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # setup python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python }}
      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact }}
          path: ${{ inputs.artifactPath }}
      - name: Sonar publish analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
          SONAR_URL: 'https://sonarcloud.io'
        run: |
          SONAR_KEY="${GITHUB_REPOSITORY//\//_}"   
          OPS="-Dsonar.projectKey=$SONAR_KEY"
          OPS="$OPS -Dsonar.host.url=$SONAR_URL"
          OPS="$OPS -Dsonar.organization=${{ github.repository_owner }}"
          OPS="$OPS -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info"
          OPS="$OPS -Dsonar.testExecutionReportPaths=./coverage/sonarqube_report.xml"
          npx sonarqube-scanner $OPS -Dsonar.token=${{ secrets.SONAR_TOKEN }}

